[package]
name = "bellman-sha256"
version = "0.1.0"
edition = "2021"
author = "Hisham Galal"

[dependencies]
bellman = "0.13.0"
sha2 = "0.10.2"
rand = "0.8.5"
ff = "0.12.0"
pairing = "0.22.0"
bls12_381 = "0.7.0"