[package]
name = "bellperson-sha256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellperson = "0.20.0"
sha2 = "0.10.2"
rand = "0.8.5"
ff = "0.12.0"
pairing = "0.22.0"
blstrs = "0.4.2"